[package]
name = "password_vault"
version = "0.1.0"
edition = "2024"

[dependencies]
age = { version = "0.10.1", features = ["armor"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
secrecy = "0.8"
rpassword = "7.2.0"

